Post/urls.py
# From Django
from django.urls import path

# From Apps
from Views import views as v
from . import views

app_name = "post"
urlpatterns = [
    path("", v.Home.as_view(), name="home"),
    path("explore/", v.Explorer.as_view(), name="explore"),
    path("create/", views.CreatePost.as_view(), name="create_post"),
    path("update/<int:pk>", views.EditPost.as_view(), name="update_post"),
    path("delete/<int:pk>", views.DeletePost.as_view(), name="delete_post"),
    path("api/like_json/<int:pk>/", views.like_json, name="like_json"),
    path("api/like/<int:pk>/", views.like, name="like"),
    path("page/<username>/", v.UserPage.as_view(), name="user_page"),
]

instagram/urls.py
# From Django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# From Apps
from User.views import Login

urlpatterns = [
    path('login/', Login.as_view(), name="login"),
    path('', include("django.contrib.auth.urls")),
    path('', include("Post.urls")),
    path('', include("User.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:  # show media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Post/models.py
# From Django
from django.db import models
from django.shortcuts import get_object_or_404

# From Apps
from User.models import User


# Managers
class PostManager(models.Manager):
    # like and dislike post
    def like_dislike(self, request, pk):
        post = get_object_or_404(self.model, pk=pk)
        if request.user not in post.like.all():
            post.like.add(request.user)
        else:
            post.like.remove(request.user)
        post.save()


# Models
class Post(models.Model):
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publisher')
    caption = models.TextField(null=True, blank=True)
    like = models.ManyToManyField(User, related_name="like", null=True, blank=True)
    published = models.DateTimeField(auto_now_add=True)
    content = models.ImageField(upload_to="images")
    objects = PostManager()

    class Meta:
        ordering = ["-published"]

    def __str__(self):
        return self.publisher.username

    def like_count(self):
        return self.like.count()

    like_count.short_description = "like count"

User/models.py
# From Django
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.html import format_html


# Managers
class ContactManager(models.Manager):
    # follow  a user
    def follow(self, request, user):
        contact = Contact.objects.create(user_from=request.user, user_to=user)
        contact.save()

    # unfollow a user
    def unfollow(self, request, user):
        return Contact.objects.get(user_from=request.user, user_to=user).delete()


# Models
class Contact(models.Model):
    # user_from is who you following
    user_from = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="rel_from_set")
    # user_to is who following you
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="rel_to_set")

    def save(self, *args, **kwargs):
        # check the following is valid
        if self.user_from == self.user_to:
            raise ValidationError("can not follow yourself")
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user_from} follows {self.user_to}"


class User(AbstractUser):
    following = models.ManyToManyField("self", through=Contact, related_name="followers")
    profile = models.ImageField(upload_to="profiles", default="profiles/default-profile-user.jpg")
    biography = models.TextField(blank=True, null=True)

    # redirect after register a user
    def get_absolute_url(self):
        return reverse("login")

    # get following count
    def following_count(self):
        return self.following.count()

    # get followers count
    def followers_count(self):
        return Contact.objects.filter(user_to=self).count()

    # show user's profile in admin panel
    def show_profile(self):
        return format_html(f"<img src='{self.profile.url}' alt={self.username}' width='60px'>")

    following_count.short_description = "following"
    followers_count.short_description = "followers"
    show_profile.short_description = "profile"

Post/views.py
# From Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from .mixins import AccessMixin
# From Apps
from .models import Post


# Create your views here.
class CreatePost(LoginRequiredMixin, CreateView):
    # create post
    model = Post
    fields = ["content", "caption"]

    # redirect after creation post
    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])

    # set publisher to self
    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.publisher = self.request.user
        return super().form_valid(form)


class EditPost(LoginRequiredMixin, AccessMixin, UpdateView):
    # edit post
    model = Post
    fields = ["caption", "content"]

    # redirect after editing post
    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])


class DeletePost(LoginRequiredMixin, AccessMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])


@login_required
# will return a json of like detail
def like_json(request, pk):
    return JsonResponse({
        "like_count": get_object_or_404(Post, pk=pk).like.count(),
        "is_liked": request.user in get_object_or_404(Post, pk=pk).like.all(),
        "pk": pk
    })


@login_required
# like a post
def like(request, pk):
    Post.objects.like_dislike(request, pk=pk)
    return JsonResponse({
        "like_count": get_object_or_404(Post, pk=pk).like.count(),
        "is_liked": request.user in get_object_or_404(Post, pk=pk).like.all(),
        "pk": pk
    })

templates/Post/popup_boxes/create-update-post-popup.html
<div class="post-form">
    <div class="title">
        <h3></h3>
    </div>
    <form action="" class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="content-input">
            <span id="label">Photo : </span>
            <input type="file" name="content" id="id_content">
        </div>
        <div class="caption-input">
            <textarea name="caption" cols="40" rows="10" id="id_caption" placeholder="Caption(optional)..."></textarea>
        </div>
        <div class="create-update">
            <button></button>
        </div>
    </form>
</div>

templates/Post/popup_boxes/delete-post-popup.html
<div class="delete-popup">
    <div class="title">
        <h3>Delete post <span id="close" style="float: right"></span></h3>
    </div>
    <div class="body">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete it?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
</div>

templates/Post/popup_boxes/detail-post-popup.html
<div class="detail-popup">
    <div class="l-side">
        <div class="image">
            <img src="" alt="">
        </div>
    </div>
    <div class="r-side">
        <div class="header">
            <div class="like">
                <button class="like-dislike" style="margin-right: 10px;"><i class="fa-heart fa-2x"></i></button>
                <span id="like-count"></span>
            </div>
            <div class="buttons">
                <button id="edit-post">Edit</button>
                <button id="delete-post">Delete</button>
            </div>
            <span id="close"></span>
        </div>
        <div class="caption">
            <span></span>
        </div>
    </div>

    <!-- Responsive -->
    <div class="t-side">
        <div class="image">
            <img src="" alt="">
        </div>
    </div>
    <div class="b-side">
        <div class="header">
            <div class="like">
                <button class="like-dislike" style="margin-right: 10px;"><i class="fa-heart fa-2x"></i></button>
                <span id="like-count"></span>
            </div>
            <div class="buttons" style="flex-grow: 0">
                <button id="edit-post">Edit</button>
                <button id="delete-post">Delete</button>
            </div>
            <span id="close"></span>
        </div>
        <div class="caption">
            <span></span>
        </div>
    </div>
</div>

templates/Post/popup_boxes/edit-profile-popup.html
<div class="edit-profile-popup">
    <div class="title">
        <h3>Update profile
            <span id="close"></span></h3>
    </div>
    <form action="" class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="username-input">
            <input type="text" name="username" maxlength="150" required="" id="id_username" placeholder="Username">
        </div>
        <div class="profile-input">
            <span id="label">Profile : </span>
            <input type="file" name="profile" id="id_profile">
        </div>
        <div class="bio-input">
            <textarea name="biography" cols="40" rows="10" id="id_biography"
                      placeholder="Biography(optional)..."></textarea>
        </div>
        <div class="update">
            <button>Update</button>
        </div>
    </form>
</div>