Post/urls.py
# From Django
from django.urls import path

# From Apps
from Views import views as v
from . import views

app_name = "post"
urlpatterns = [
    path("", v.Home.as_view(), name="home"),
    path("explore/", v.Explorer.as_view(), name="explore"),
    path("create/", views.CreatePost.as_view(), name="create_post"),
    path("update/<int:pk>", views.EditPost.as_view(), name="update_post"),
    path("delete/<int:pk>", views.DeletePost.as_view(), name="delete_post"),
    path("api/like_json/<int:pk>/", views.like_json, name="like_json"),
    path("api/like/<int:pk>/", views.like, name="like"),
    path("page/<username>/", v.UserPage.as_view(), name="user_page"),
]

User/urls.py
# From Django
from django.urls import path

# From Apps
from . import views

app_name = "user"
urlpatterns = [
    path('register/', views.Register.as_view(), name="register"),
    path('update-profile/<int:pk>', views.EditProfile.as_view(), name="update-profile"),
    path("follow_unfollow/<username>/", views.follow_unfollow, name="follow_unfollow"),
    path("api/following/<username>/", views.following_json, name="following_json"),
]

instagram/urls.py
# From Django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# From Apps
from User.views import Login

urlpatterns = [
    path('login/', Login.as_view(), name="login"),
    path('', include("django.contrib.auth.urls")),
    path('', include("Post.urls")),
    path('', include("User.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:  # show media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Post/models.py
# From Django
from django.db import models
from django.shortcuts import get_object_or_404

# From Apps
from User.models import User


# Managers
class PostManager(models.Manager):
    # like and dislike post
    def like_dislike(self, request, pk):
        post = get_object_or_404(self.model, pk=pk)
        if request.user not in post.like.all():
            post.like.add(request.user)
        else:
            post.like.remove(request.user)
        post.save()


# Models
class Post(models.Model):
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publisher')
    caption = models.TextField(null=True, blank=True)
    like = models.ManyToManyField(User, related_name="like", null=True, blank=True)
    published = models.DateTimeField(auto_now_add=True)
    content = models.ImageField(upload_to="images")
    objects = PostManager()

    class Meta:
        ordering = ["-published"]

    def __str__(self):
        return self.publisher.username

    def like_count(self):
        return self.like.count()

    like_count.short_description = "like count"

Post/views.py
# From Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from .mixins import AccessMixin
# From Apps
from .models import Post


# Create your views here.
class CreatePost(LoginRequiredMixin, CreateView):
    # create post
    model = Post
    fields = ["content", "caption"]

    # redirect after creation post
    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])

    # set publisher to self
    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.publisher = self.request.user
        return super().form_valid(form)


class EditPost(LoginRequiredMixin, AccessMixin, UpdateView):
    # edit post
    model = Post
    fields = ["caption", "content"]

    # redirect after editing post
    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])


class DeletePost(LoginRequiredMixin, AccessMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return reverse("post:user_page", args=[self.request.user.username])


@login_required
# will return a json of like detail
def like_json(request, pk):
    return JsonResponse({
        "like_count": get_object_or_404(Post, pk=pk).like.count(),
        "is_liked": request.user in get_object_or_404(Post, pk=pk).like.all(),
        "pk": pk
    })


@login_required
# like a post
def like(request, pk):
    Post.objects.like_dislike(request, pk=pk)
    return JsonResponse({
        "like_count": get_object_or_404(Post, pk=pk).like.count(),
        "is_liked": request.user in get_object_or_404(Post, pk=pk).like.all(),
        "pk": pk
    })

templates/Post/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.2-web/css/all.css' %}">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'favicon/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/popup-boxes.css' %}">
    {% block link %}
    {% endblock %}
</head>
<body>
<!-- Navbar -->
{% include 'Post/navbar.html' %}
{% include 'Post/popup_boxes/create-update-post-popup.html' %}
{% include 'Post/popup_boxes/delete-post-popup.html' %}
<!-- Main -->
{% block main %}
{% endblock %}

<script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'AllStaticFiles/js/script.js' %}"></script>
<script src="{% static 'AllStaticFiles/js/post-form.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/Post/explore.html
{% extends 'Post/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/explore-home.css' %}">
{% endblock %}
{% block main %}
    <div class="container">
        <div class="post-container">
            <div class="posts">
                {% for object in object_list %}
                    <article class="post">
                        <header class="post-header">
                            <div class="profile">
                                <img src="{{ object.publisher.profile.url }}" alt="user profile">
                            </div>
                            <div class="username">
                                    <span><a href="{% url 'post:user_page' object.publisher.username %}">
                                    {{ object.publisher.username }}</a></span>
                            </div>
                        </header>
                        <div class="post-image">
                            <img src="{{ object.content.url }}" alt="{{ object.caption }}">
                        </div>
                        <div class="post-like">
                            <button class="like-dislike" data-phref="{% url 'post:like_json' object.pk %}"
                                    data-href="{% url 'post:like' object.pk %}"><i class="fa-heart fa-2x"></i></button>
                            <span></span>
                        </div>
                        <div class="post-caption">
                            <a href="{% url 'post:user_page' object.publisher.username %}">
                                <b>{{ object.publisher.username }}</b>
                            </a>
                            <span>{{ object.caption }}</span>
                        </div>
                        <div class="post-published">
                            <time>{{ object.published }}</time>
                        </div>
                    </article>
                {% empty %}
                    <h1 id="no-post">There isn't any post to show.</h1>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'AllStaticFiles/js/like-dislike.js' %}"></script>
{% endblock %}

templates/Post/home.html
{% extends 'Post/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/explore-home.css' %}">
{% endblock %}

{% block main %}
    <div class="container">
        <div class="post-container">
            <div class="posts">
                {% for objects in object_list %}
                    {% for object in objects %}
                        <article class="post">
                            <header class="post-header">
                                <div class="profile">
                                    <img src="{{ object.publisher.profile.url }}" alt="user profile">
                                </div>
                                <div class="username">
                                    <span><a href="{% url 'post:user_page' object.publisher.username %}">
                                    {{ object.publisher.username }}</a></span>
                                </div>
                            </header>
                            <div class="post-image">
                                <img src="{{ object.content.url }}" alt="{{ object.caption }}">
                            </div>
                            <div class="post-like">
                                <button class="like-dislike" data-phref="{% url 'post:like_json' object.pk %}"
                                        data-href="{% url 'post:like' object.pk %}"><i class="fa-heart fa-2x"></i>
                                </button>
                                <span></span>
                            </div>
                            <div class="post-caption">
                                <a href="{% url 'post:user_page' object.publisher.username %}">
                                    <b>{{ object.publisher.username }}</b>
                                </a>
                                <span>{{ object.caption }}</span>
                            </div>
                            <div class="post-published">
                                <time>{{ object.published }}</time>
                            </div>
                        </article>
                    {% endfor %}
                {% empty %}
                    <h1 id="no-post">There isn't any post to show.</h1>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'AllStaticFiles/js/like-dislike.js' %}"></script>
{% endblock %}

templates/Post/navbar.html
{% load static %}
<div class="nav-container">
    <div class="nav">
        <div class="logo">
            <a href="{% url 'post:home' %}"><img src="{% static 'AllStaticFiles/images/instagram.png' %}"
                                                 alt="instagram"></a>
        </div>
        <div class="shortcuts">
            <div class="home">
                <a href="{% url 'post:home' %}"><i class="fas fa-home fa-2x" title="Home"></i></a>
            </div>
            <div class="explore">
                <a href="{% url 'post:explore' %}"><i class="fas fa-search fa-2x" title="Explore"></i></a>
            </div>
            <div class="create-post">
                <i class="fas fa-camera fa-2x" title="Create post"></i>
            </div>
            <div class="profile-popup">
                <i class="fas fa-user fa-2x"></i>
                <div class="submenu">
                    <a class="profile" href="{% url 'post:user_page' user.username %}">
                        <span><i class="fas fa-user"></i> Profile</span>
                    </a>
                    <a class="logout" href="{% url 'logout' %}">
                        <span><i class="fas fa-sign-out-alt"></i> Logout</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/Post/ownPage.html
{% extends 'Post/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/usersPage-ownPage.css' %}">
{% endblock %}
{% block main %}
    {% include 'Post/popup_boxes/edit-profile-popup.html' %}
    {% include 'Post/popup_boxes/detail-post-popup.html' %}


    <div class="container">
        <div class="detail-container">
            <div class="profile-photo">
                <img src="{{ User.profile.url }}" alt="{{ User.username }}">
            </div>
            <div class="detail">
                <div class="meta">
                    <div class="username">
                        <h1>{{ User.username }}</h1>
                    </div>
                    <div class="edit-profile">
                        <button data-pk="{{ User.pk }}">Edit Profile</button>
                    </div>
                </div>
                <div class="follower-following">
                    <div class="post-count">
                        <span>{{ post_count }} post</span>
                    </div>
                    <div class="followers-count">
                        <span>{{ User.followers_count }} followers</span>
                    </div>
                    <div class="following-count">
                        <span>{{ User.following_count }} following</span>
                    </div>
                </div>
                <div class="biography">
                    <span>
                        {% if User.biography %}
                            {{ User.biography }}
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
        <div class="detail-responsive">
            <div class="post-count">
                <span>{{ post_count }} post</span>
            </div>
            <div class="followers-count">
                <span>{{ User.followers_count }} followers</span>
            </div>
            <div class="following-count">
                <span>{{ User.following_count }} following</span>
            </div>
        </div>
        <div class="posts-container">
            {% for objects in object_list %}
                <div class="post-row">
                    {% for object in objects %}
                        <div class="post">
                            <img src="{{ object.content.url }}" alt="{{ object.caption }}"
                                 data-pk="{{ object.pk }}"
                                 data-href="{% url 'post:like' object.pk %}"
                                 data-phref="{% url 'post:like_json' object.pk %}">
                        </div>
                    {% endfor %}
                </div>
            {% empty %}
                <h2>Click on camera icon  in the navbar to add a post.</h2>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'AllStaticFiles/js/post-detail.js' %}"></script>
    <script src="{% static 'AllStaticFiles/js/like-dislike.js' %}"></script>
    <script src="{% static 'AllStaticFiles/js/edit-profile.js' %}"></script>
{% endblock %}

templates/Post/usersPage.html
{% extends 'Post/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'AllStaticFiles/css/usersPage-ownPage.css' %}">
{% endblock %}
{% block main %}
    {% include 'Post/popup_boxes/detail-post-popup.html' %}

    <div class="container">
        <div class="detail-container">
            <div class="profile-photo">
                <img src="{{ User.profile.url }}" alt="{{ User.username }}">
            </div>
            <div class="detail">
                <div class="meta">
                    <div class="username">
                        <h1>{{ User.username }}</h1>
                    </div>
                    <div class="follow-unfollow">
                        <button data-href="{% url 'user:follow_unfollow' User.username %}"
                        data-phref="{% url 'user:following_json' User.username %}"></button>
                    </div>
                </div>
                <div class="follower-following">
                    <div class="post-count">
                        <span>{{ post_count }} post</span>
                    </div>
                    <div class="followers-count">
                        <span>{{ User.followers_count }} followers</span>
                    </div>
                    <div class="following-count">
                        <span>{{ User.following_count }} following</span>
                    </div>
                </div>
                <div class="biography">
                    <span>
                        {% if User.biography %}
                            {{ User.biography }}
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
        <div class="detail-responsive">
            <div class="post-count">
                <span>{{ post_count }} post</span>
            </div>
            <div class="followers-count">
                <span>{{ User.followers_count }} followers</span>
            </div>
            <div class="following-count">
                <span>{{ User.following_count }} following</span>
            </div>
        </div>
        <div class="posts-container">
            {% for objects in object_list %}
                <div class="post-row">
                    {% for object in objects %}
                        <div class="post">
                            <img src="{{ object.content.url }}" alt="{{ object.caption }}"
                            data-pk="{{ object.pk }}"
                            data-href="{% url 'post:like' object.pk %}"
                            data-phref="{% url 'post:like_json' object.pk %}">
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'AllStaticFiles/js/follow-unfollow.js' %}"></script>
    <script src="{% static 'AllStaticFiles/js/post-detail.js' %}"></script>
    <script src="{% static 'AllStaticFiles/js/like-dislike.js' %}"></script>
{% endblock %}